### ISSUE TITLE
Interpretive content for Collection artworks

### ISSUE THREAD

**Issue by swambold6** [stillmuseum/patricia#107]
@halfempty (from our discussions just before launch...stay tuned before moving forward)

Interpretive content (extended captions/labels) for Collection (artwork) items (with template adjustments accordingly)

**Comment by halfempty** [comment]
@swambold6 Okay, so I think a simple logic change might work here.

A refresher: For Archive pieces, we're showing caption on the left and content in the middle. For Collection pieces, we're showing caption in the middle and disregarding content.

So I've changed it so that instead of distinguising between Archive and Collection pieces, we're instead looking at if the content is blank or not. If there's content, we do it the "Archives way." If there's no content, we do it the "Collection way." And it doesn't matter about the categories.

As an example, see what happens when you remove the Lorem Ipsum content from here:

https://dev.clyffordstillmuseum.org/object/pp-539/

Cool?

**Comment by swambold6** [comment]
Perfect!  Exactly what I'd hoped for.  Thanks!

**Comment by swambold6** [comment]
Ooops.  Closed too fast...please commit to public-facing site when you're ready.
