### ISSUE TITLE
"In same term" for Previous/Next links

### ISSUE THREAD

**Issue by halfempty** [stillmuseum/patricia#124]
**@swambold6 says:**

> Previous / Next Events don't "remember" what Event category you came from. For instance, if you click into a program from the Public Programs page and click Next Event, it's likely you will see a Daily Tour, rather than the next Public Program Event.

**Comment by halfempty** [comment]
@swambold6 When working with Posts, WP has a useful parameter called "in same term" that does what you're asking here. The Event plugin doesn't provide an equivilant parameter, unfortunately. I've posted to their support forum to see if they can help me add one.

**Comment by swambold6** [comment]
Sounds good.  Thanks, Marty!

On Thu, May 28, 2015 at 3:40 PM, Marty Spellerberg <notifications@github.com
> wrote:

> @swambold6 <https://github.com/swambold6> When working with Posts, WP has
> a useful parameter called "in same term" that does what you're asking here.
> The Event plugin doesn't provide an equivilant parameter, unfortunately.
> I've posted to their support forum to see if they can help me add one.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stillmuseum/patricia/issues/124#issuecomment-106607943>
> .
>



-- 
Best regards,
Sarah Wambold

swambold.com

**Comment by halfempty** [comment]
@swambold6 The forum guys responded, basically, "yeah, you're on your own with this one." So I'll write a custom funciton.

**Comment by halfempty** [comment]
@swambold6 Just a note to say I've been toiling on this one, but haven't quite gotten it working yet

**Comment by halfempty** [comment]
@swambold6 I'm tempted to concede defeat on this one. However, if this issue's really been bugging you please reopen.

**Comment by swambold6** [comment]
@halfempty I'm going down a bit of a rabbit hole on this one. I looked in GA to see how much those buttons are being used on the site, but it appears I can't get that data anymore without using Tag Manager ... ? Did you have to set up Tag Manager when you created the VMS on our site?

It does bug me that this doesn't work. I'd be willing to let it go if we find that users are not navigating that way. But I'm inclined to keep it open for now so that we don't lose it in the six pages of closed issues.
