### ISSUE TITLE
Embed video on architecture page

### ISSUE THREAD

**Issue by swambold6** [stillmuseum/patricia#145]
How can we embed a Vimeo video (this one: https://vimeo.com/169135596) on the architecture page (https://clyffordstillmuseum.org/architecture)?

**Comment by halfempty** [comment]
@swambold6 Nice! Is this the one you've been working on? 

I can add an option for a "Video" row to that template.

**Comment by swambold6** [comment]
@halfempty Thanks! Yeah, I've been working on this one for a little while. Alfini did the post. I'm really happy with it!

Re: video row: sounds great. Any recommendations on what the embed size should be?

**Comment by halfempty** [comment]
@swambold6 Would you like it to be full-width, like an image? We can also put a image on top, with a "play" icon

**Comment by swambold6** [comment]
@halfempty I'd love it to be full-width, if possible. I'm ok with the preview being the one coming out of Vimeo. I'm ok with the preview—image (I've uploaded my own to Vimeo) and play button—straight out of the Vimeo embed code. But open to your suggestion.

**Comment by halfempty** [comment]
@swambold6 Okay, please take a look:

http://dev.clyffordstillmuseum.org/about-the-building/

**Comment by swambold6** [comment]
@halfempty Looks great! John and I are totally in to this!

Only one tweak ... I missed the play button entirely when I first looked at the page. Could we possible "borrow" from the style for the Home button on our site, possibly rolling over to CSM red or the like? Totally open to your suggestions here.

But overall, incredibly elegant! Very excited about this!

One more question, looks like all we need from Vimeo is the url. Is that right? I was playing around with the embed settings in Vimeo, but it looks like the CMS is stripping all that out, right? (Which is totally awesome and fantastic and wonderful if so.)

**Comment by halfempty** [comment]
@swambold6 More like this? Or is this TOO visible? http://dev.clyffordstillmuseum.org/about-the-building/

**Comment by swambold6** [comment]
@halfempty Super! Push it to the live site, please! 👍

**Comment by halfempty** [comment]
@swambold6 I've applied the code, but there's a bug. It appeared in Dev but I thought I'd found and fixed it. Unfortunately, it's persisting on Live. I'll keep you updated as I make progress.

**Comment by halfempty** [comment]
@swambold6 This bug is continuing to prevent me from launching. I'll explain what's happening, so you know:

WP uses something called oEmbed to convert video URLs into iframe players. Additionally, WP recently added the ability to embed blog posts via oEmbed, allowing people to embed Posts just like they embed Videos. (I actually don't know why they did this. Who needs it?) Something's malfunctioning with these pieces. 

Instead of returning the video embed code, oEmbed is returning an embed of the next upcoming Event, from our very own site! Weird. Originally, I thought I'd fixed the problem by upgrading the Events plugin to the latest version. Unfortunately, the bug persists. And worse, I've been unable to reproduce the issue on a fresh install, which is a necessary prerequisite to filing a bug report with the Events people. I've also tried disabling the embed-Post functionality, but haven't had success.

Having spent a few hours unable to isolate the issue, now I'm considering trying to find a work-around. This would likely involve using the Vimeo-supplied embed iFrame, rather than oEmbed. I'll begin to re-work the code around that approach.

However, this is something we may want to get to the bottom of for the video Channel project. I do think the problem's in the Events plugin, but need to be able to reliably reproduce it.

**Comment by halfempty** [comment]
@swambold6 Okay, work-around done and video added to live site!

I look forward to isolating (and squashing!) the oEmbed bug as part of the Video Kiosk project.
