### ISSUE TITLE
Call to Action strip on Private Events page

### ISSUE THREAD

**Issue by halfempty** [stillmuseum/patricia#162]

**Comment by swambold6** [comment]
@halfempty The issue + description probably needs to be updated based on most recent conversations...

Lydia is fine removing the Private Events page from the navigation, and doesn't seem to care what the link in the navigation is called. Therefore, I think it can stay "Museum Rentals."

She *would* like a more involved form for inquiries. I'm thinking the link to the form still lives in the strip, rather than a lengthy form on the page. (I'd rather have the click through to the form for someone who is seriously interested, than a click through to more information while the person is still shopping.)

She would also like the ability to categorize images in the gallery by type: Weddings, Corporate Events, etc. I'll have her come up with a list for categories and we'll see how many she comes up with. But for the time being, know that she's picturing something akin to the way the collection thumbnails are broken out by type/category. We'll wait to make that call when we know what the content is, but wanted to give you a heads up
