### ISSUE TITLE
forward/backward arrows in Collection/Archives

### ISSUE THREAD

**Issue by swambold6** [stillmuseum/patricia#79]
@halfempty For post-launch (pre-launch, if possible) a way to navigate forward and backward in Collection and Archive items from the individual pages.

**Comment by halfempty** [comment]
@swambold6 Okay, some progress on this...

Since we already are using our "back button" style for the "Back to Collection/Back to Archive" link, I'm thinking we should omit a "Previous Object" link.

I have put in a "Next Object" link, though. It's going to look for the next object within either Collection or Archives. It's going to disregard the subcategories, 'cause that would get into some very complex custom programming. The "next" object will mean the one with the next higher Menu Order. 

(I should mention that by using both Object Categories and Menu Order on these things we're going somewhat against WP convention. Menu Order is usually for Page-like objects, which are organized via hierarchy. Categories are usually used with Post-like objects, which are then ordered by date.)

**Comment by halfempty** [comment]
@swambold6 Okay, you can now set the "Sort Order" on the live site. The front-end display is still by date, so you can make the Sort Order match the current display.
